apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: cd-pipeline-customers-run-3
  namespace: mfrieri-dev
spec:
  pipelineRef:
    name: cd-pipeline-customers
  params:
    - name: git-url
      value: https://github.com/CSCI-GA-2820-FA25-001/customers
    - name: git-ref
      value: master
    - name: image-name
      value: image-registry.openshift-image-registry.svc:5000/mfrieri-dev/customers:master
    - name: app-name
      value: customers
    - name: base-url
      value: http://customers:8080
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: pipeline-workspace
