---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo
spec:
  workspaces:
    - name: pipeline-workspace
  steps:
    - name: echo
      image: registry.access.redhat.com/ubi9/ubi-minimal:latest
      script: |
        echo "Pipeline is running"

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: checkout
spec:
  params:
    - name: url
    - name: revision
      default: main
  workspaces:
    - name: pipeline-workspace
  steps:
    - name: clone
      image: alpine/git
      script: |
        cd $(workspaces.pipeline-workspace.path)
        rm -rf repo || true
        git clone $(params.url) repo
        cd repo
        git checkout $(params.revision)

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: lint
spec:
  params:
      - name: path
        default: service
  workspaces:
    - name: source
  steps:
    - name: run-lint
      image: python:3.10
      script: |
        cd $(workspaces.source.path)/repo
        # Install everything first
        pip install flake8 pylint pipenv flask-restx
        pipenv install --dev --system
        # Then run lint checks
        flake8 $(params.path) tests || exit 1
        pylint $(params.path) tests || exit 1

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: tests
spec:
  workspaces:
    - name: source
  steps:
    - name: run-tests
      image: python:3.11
      env:
        - name: DATABASE_URI
          value: "sqlite:///$(workspaces.source.path)/test.db"
      script: |
        cd $(workspaces.source.path)/repo
        pip install pipenv flask-restx
        pipenv install --dev --system
        pytest --pspec

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-image
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: Deployment
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: openshift, deploy
    tekton.dev/displayName: "deploy image"
    tekton.dev/platforms: "linux/amd64"
spec:
  workspaces:
  - name: source  
  description: >-
    This task will update the deployment.yaml with the latest image name
    and then apply that yaml file and it's service file.
  params:
  - name: image-name
    description: The fully qualified name of the new image to deploy
    type: string
  - name: manifest-dir
    description: The directory in source that contains yaml manifests
    type: string
    default: "k8s"
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source/repo
      command: ["/bin/bash", "-c"]
      args:
        - |-
          #!/bin/bash
          set -e

          echo "**********************************************************************"
          echo "Installing YQ..."
          echo "**********************************************************************"
          wget -qO /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          chmod a+x /usr/bin/yq

          echo "*********************  DEPLOYMENT  ***********************"
          echo "Deploying $(params.image-name) ..."

          yq -e -i '.spec.template.spec.containers[0].image="$(params.image-name)"' $(params.manifest-dir)/deployment.yaml
          cat $(params.manifest-dir)/deployment.yaml

          echo "************************************************************"
          echo "OC APPLY..."
          oc apply -f $(params.manifest-dir)/deployment.yaml
          oc apply -f $(params.manifest-dir)/service.yaml

          echo "************************************************************"
          sleep 3
          echo "Pods:"
          oc get pods
          echo ""

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: behave
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/categories: Testing
    tekton.dev/pipelines.minVersion: "0.17.0"
    tekton.dev/tags: python, bdd, behave
    tekton.dev/displayName: "bdd tests"
    tekton.dev/platforms: "linux/amd64"
spec:
  workspaces:
    - name: source
  description: >-
    This task can be used to perform bdd tests with behave.
  params:
    - name: base-url
      description: The url of the application to test
      type: string
    - name: wait-seconds
      description: The number of seconds to wait for a reply
      type: string
      default: "60"
    - name: driver
      description: The web driver to use (chrome or firefox)
      type: string
      default: "chrome"
  steps:
    - name: behave
      image: quay.io/rofrano/pipeline-selenium
      workingDir: $(workspaces.source.path)/repo
      env:
       - name: BASE_URL
         value: $(params.base-url)
       - name: WAIT_SECONDS
         value: $(params.wait-seconds)
       - name: DRIVER
         value: $(params.driver)
      script: |
        #!/bin/bash
        set -e
        export PATH=$PATH:$HOME/.local/bin

        echo "***** Installing dependencies *****"
        if [ -e "Pipfile" ]; then
          echo "Found Pipfile: using pipenv"
          python -m pip install --upgrade pip pipenv
          pipenv requirements --dev > requirements.txt
        elif [ ! -e "requirements.txt" ]; then
          echo "No requirements file found"
          exit 1
        fi
        python -m pip install --user -r requirements.txt

        echo "***** Running BDD Tests *****"
        behave
