kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pipeline-pvc-2
  namespace: mfrieri-dev
  uid: 3ad6a9ae-46ee-4f64-8184-8e01cb5c4f23
  resourceVersion: '5353181053'
  creationTimestamp: '2025-12-08T17:13:32Z'
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/selected-node: ip-10-0-52-132.ec2.internal
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
  finalizers:
    - kubernetes.io/pvc-protection
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2025-12-08T17:13:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:accessModes': {}
          'f:resources':
            'f:requests':
              .: {}
              'f:storage': {}
          'f:storageClassName': {}
          'f:volumeMode': {}
    - manager: kube-scheduler
      operation: Update
      apiVersion: v1
      time: '2025-12-08T17:28:30Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:volume.kubernetes.io/selected-node': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-12-08T17:28:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:pv.kubernetes.io/bind-completed': {}
            'f:pv.kubernetes.io/bound-by-controller': {}
            'f:volume.beta.kubernetes.io/storage-provisioner': {}
            'f:volume.kubernetes.io/storage-provisioner': {}
        'f:spec':
          'f:volumeName': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2025-12-08T17:28:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:phase': {}
      subresource: status
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-3ad6a9ae-46ee-4f64-8184-8e01cb5c4f23
  storageClassName: gp3
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
